name: GH-200
on: push
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello from GH-200 seesion from microsoft"

      - name: copy code into runner
        uses: actions/checkout@v7

      - name: List files
        run: ls -la
